added validation that column names are unique in export to SPSS
tidyverse/haven pull request #643
Opened 2021-09-28 19:42 UTC by juansebastianl

A fix to issue #641

2021-09-28 19:52 UTC, juansebastianl commented
I don't know how to add tests here, but this PR is something that can easily be unit tested.

2021-09-29 10:46 UTC, gorcha requested changes
Thanks for the contribution! I've made a few comments, just style related stuff.

Can you please add a bullet to the top of `NEWS.md`? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

Regarding a unit test - a good reference for adding a test covering this functionality is the Stata variable name checks in "test-haven-stata.R" (this tests the checks for variable names that are too long or include invalid characters, so it's a little different but the same general idea):
https://github.com/tidyverse/haven/blob/eb5e8c9fe2b56b269079942690452c53993b5ac6/tests/testthat/test-haven-stata.R#L217-L230

2021-09-29 10:46 UTC, gorcha commented on R/haven-spss.R
> +    stop(
Error messages should have `call. = FALSE` to  [exclude call information](https://style.tidyverse.org/error-messages.html#problem-statement).

2021-09-29 10:46 UTC, gorcha commented on R/haven-spss.R
> +      "column(s) \"", paste(col_names[duplicated(tolower(col_names))], collapse = "\" \""), "\" not unique\n",
Variable names should be [surrounded by backticks](https://style.tidyverse.org/error-messages.html#punctuation) instead of double quotes - haven has a handy internal `var_names()` helper for this, see `bad_lengths` below for an example.

2021-09-29 10:46 UTC, gorcha commented on R/haven-spss.R
> +  unique_colnames <- unique(tolower(names(data)))
Not essential, just a suggestion - a cleaner way to do this might be to create a `dupe_vars <- duplicated(tolower(names(data)))` to avoid having to perform the duplicate check in both the if statement and the column name filtering in the error message.

2021-09-29 11:08 UTC, gorcha commented on R/haven-spss.R
> +  if(length(col_names) != length(unique_colnames)){
Place a [space before and after `()`](https://style.tidyverse.org/syntax.html#spacing) when used with `if`, `for`, or `while`.

2022-02-27 05:08 UTC, gorcha commented
Hi @juansebastianl, I've opened a new PR with a little clean up of this check and some tests added alongside a couple of other new variable name validation rules in #660, so closing this off.

Thanks again for the contribution, very much appreciated! :slightly_smiling_face:

2022-02-27 05:08 UTC, closed without merging